kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: poao-tilgang
  namespace: poao
  labels:
    team: poao
spec:
  image: ghcr.io/navikt/poao-tilgang/poao-tilgang:{{version}}
  port: 8080
  ingresses:
    - https://poao-tilgang.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      claims:
        extra:
          - azp_name
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
          namespace: amt
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
        - application: veilarbportefolje
          namespace: pto
          cluster: dev-fss
        - application: veilarbveileder
          namespace: pto
          cluster: dev-fss
    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom
  env:
    - name: MICROSOFT_GRAPH_SCOPE
      value: https://graph.microsoft.com/.default
    - name: MICROSOFT_GRAPH_URL
      value: https://graph.microsoft.com
    - name: SKJERMET_PERSON_SCOPE
      value: api://dev-gcp.nom.skjermede-personer-pip/.default
    - name: SKJERMET_PERSON_URL
      value: http://skjermede-personer-pip.nom.svc.cluster.local
    - name: POAO_GCP_PROXY_SCOPE
      value: api://dev-fss.pto.poao-gcp-proxy/.default
    - name: POAO_GCP_PROXY_URL
      value: https://poao-gcp-proxy.dev-fss-pub.nais.io
    - name: AXSYS_SCOPE
      value: api://dev-fss.org.axsys/.default
    - name: ABAC_URL
      value: https://abac-veilarb-proxy.dev-fss-pub.nais.io/api/proxy/abac
    - name: ABAC_SCOPE
      value: api://dev-fss.pto.abac-veilarb-proxy/.default
    - name: VEILARBARENA_URL
      value: https://veilarbarena.dev-fss-pub.nais.io/veilarbarena
    - name: VEILARBARENA_SCOPE
      value: api://dev-fss.pto.veilarbarena/.default
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: RUNTIME_LOCATION
      value: GCP
