kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: poao-tilgang
  namespace: poao
  labels:
    team: poao
spec:
  image: ghcr.io/navikt/poao-tilgang/poao-tilgang:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 22
  liveness:
    path: /internal/health/liveness
    initialDelay: 22
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name
  secureLogs:
    enabled: true
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefolje
          namespace: pto
        - application: veilarbveileder
          namespace: pto
        - application: veilarbvedtaksstotte
          namespace: pto
        - application: pto-admin
          namespace: pto
        - application: veilarbfilter
          namespace: pto
        - application: veilarbarena
          namespace: pto
        - application: veilarbperson
          namespace: pto
        - application: veilarboppgave
          namespace: pto
        - application: veilarboppfolging
          namespace: pto
        - application: veilarbvedtakinfo
          namespace: pto
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom
      external:
        - host: graph.microsoft.com
        - host: unleash.nais.io
  env:
    - name: spring_profiles_active
      value: fss
    - name: MICROSOFT_GRAPH_SCOPE
      value: https://graph.microsoft.com/.default
    - name: MICROSOFT_GRAPH_URL
      value: https://graph.microsoft.com
    - name: SKJERMET_PERSON_SCOPE
      value: api://dev-fss.nom.skjermede-personer-pip/.default
    - name: SKJERMET_PERSON_URL
      value: http://skjermede-personer-pip.nom.svc.nais.local
    - name: AXSYS_URL
      value: http://axsys.org.svc.nais.local
    - name: AXSYS_SCOPE
      value: api://dev-fss.org.axsys/.default
    - name: ABAC_URL
      value: http://abac-veilarb-q1.pto.svc.nais.local/application/asm-pdp/authorize
    - name: VEILARBARENA_URL
      value: http://veilarbarena.pto.svc.nais.local/veilarbarena
    - name: VEILARBARENA_SCOPE
      value: api://dev-fss.pto.veilarbarena/.default
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: http://pdl-api.pdl.svc.nais.local
    - name: UNLEASH_URL
      value: https://unleash.nais.io/api/
    - name: NORG_URL
      value: http://norg2.org.svc.nais.local
    - name: AD_GRUPPE_ID_FORTROLIG_ADRESSE
      value: ea930b6b-9397-44d9-b9e6-f4cf527a632a
    - name: AD_GRUPPE_ID_STRENGT_FORTROLIG_ADRESSE
      value: 5ef775f2-61f8-4283-bf3d-8d03f428aa14
    - name: AD_GRUPPE_ID_MODIA_ADMIN
      value: fd0e475e-698b-4bcd-aa62-7540433f3e80
    - name: AD_GRUPPE_ID_MODIA_OPPFOLGING
      value: 554a66fb-fbec-4b92-90c1-0d9c085c362c
    - name: AD_GRUPPE_ID_MODIA_GENERELL
      value: 67a06857-0028-4a90-bf4c-9c9a92c7d733
    - name: AD_GRUPPE_ID_GOSYS_NASJONAL
      value: 924badcd-b936-44f4-b7bf-97c03de0893a
    - name: AD_GRUPPE_ID_GOSYS_UTVIDBAR_TIL_NASJONAL
      value: 2ffe3262-6c0e-44f3-94f0-34dfa5659a04
    - name: AD_GRUPPE_ID_SYFO_SENSITIV
      value: c8957e0a-909c-4b62-8e11-93aae6d295e6
    - name: AD_GRUPPE_ID_EGNE_ANSATTE
      value: dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
    - name: AD_GRUPPE_ID_AKTIVITETSPLAN_KVP
      value: 1e9ea264-ab56-44a0-afa1-3f59ce192484
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srv-poao-tilgang
        mountPath: /var/run/secrets/nais.io/service_user
