kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: poao-tilgang
  namespace: poao
  labels:
    team: poao
spec:
  image: ghcr.io/navikt/poao-tilgang/poao-tilgang:{{version}}
  port: 8080
  ingresses:
    - https://poao-tilgang.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  env:
    - name: MICROSOFT_GRAPH_SCOPE
      value: https://graph.microsoft.com/.default
    - name: MICROSOFT_GRAPH_URL
      value: https://graph.microsoft.com
    - name: SKJERMET_PERSON_SCOPE
      value: api://prod-gcp.nom.skjermede-personer-pip/.default
    - name: SKJERMET_PERSON_URL
      value: http://skjermede-personer-pip.nom.svc.cluster.local
