kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: poao-tilgang
  namespace: poao
  labels:
    team: poao
spec:
  image: ghcr.io/navikt/poao-tilgang/poao-tilgang:{{version}}
  port: 8080
  ingresses:
    - https://poao-tilgang.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      claims:
        extra:
          - azp_name
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
          namespace: amt
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
        - application: veilarbportefolje
          namespace: pto
          cluster: prod-fss
        - application: veilarbveileder
          namespace: pto
          cluster: prod-fss
    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom
  env:
    - name: MICROSOFT_GRAPH_SCOPE
      value: https://graph.microsoft.com/.default
    - name: MICROSOFT_GRAPH_URL
      value: https://graph.microsoft.com
    - name: SKJERMET_PERSON_SCOPE
      value: api://prod-gcp.nom.skjermede-personer-pip/.default
    - name: SKJERMET_PERSON_URL
      value: http://skjermede-personer-pip.nom.svc.cluster.local
    - name: POAO_GCP_PROXY_SCOPE
      value: api://prod-fss.pto.poao-gcp-proxy/.default
    - name: POAO_GCP_PROXY_URL
      value: https://poao-gcp-proxy.prod-fss-pub.nais.io
    - name: AXSYS_URL
      value: https://axsys.prod-fss-pub.nais.io
    - name: AXSYS_SCOPE
      value: api://prod-fss.org.axsys/.default
    - name: ABAC_URL
      value: https://abac-veilarb-proxy.prod-fss-pub.nais.io/api/proxy/abac
    - name: ABAC_SCOPE
      value: api://prod-fss.pto.abac-veilarb-proxy/.default
    - name: VEILARBARENA_URL
      value: https://veilarbarena.prod-fss-pub.nais.io/veilarbarena
    - name: VEILARBARENA_SCOPE
      value: api://prod-fss.pto.veilarbarena/.default
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: RUNTIME_LOCATION
      value: GCP
    - name: AD_GRUPPE_ID_FORTROLIG_ADRESSE
      value: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
    - name: AD_GRUPPE_ID_STRENGT_FORTROLIG_ADRESSE
      value: ad7b87a6-9180-467c-affc-20a566b0fec0
    - name: AD_GRUPPE_ID_MODIA_ADMIN
      value: dd1aacab-7e63-47fc-9d8f-852dc736ed98 # Må oppdateres
    - name: AD_GRUPPE_ID_MODIA_OPPFOLGING
      value: b9bc6348-d25c-450d-85c2-044c0955fbe3
    - name: AD_GRUPPE_ID_MODIA_GENERELL
      value: ea34edea-1e80-4759-a1d2-fbe696cf1709
    - name: AD_GRUPPE_ID_GOSYS_NASJONAL
      value: 3063daf5-24c6-409c-9139-2d843cb4327b
    - name: AD_GRUPPE_ID_GOSYS_UTVIDBAR_TIL_NASJONAL
      value: ad3ee064-44b7-4c58-a618-5df1e1cb05db
    - name: AD_GRUPPE_ID_GOSYS_UTVIDET
      value: 73ff0e76-f2b1-4586-8387-b33f15617381
    - name: AD_GRUPPE_ID_SYFO_SENSITIV
      value: 100e88eb-79af-4136-8bfe-f79b32021f43
    - name: AD_GRUPPE_ID_PENSJON_UTVIDET
      value: 676b5e1f-84e6-46e5-8814-04233699ed4b
