name: Deploy feature branch to dev
run-name: Deploy feature branch ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/poao-tilgang/actions/workflows/deploy-feature-dev.yaml

concurrency:
  group: deploy-feature-branch
  cancel-in-progress: true

env:
  PRINT_PAYLOAD: true

jobs:
  test-build-and-push:
    name: Test, build and push
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'
      - name: Build maven artifacts
        run: mvn -B package
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: poao

  deploy-dev:
    name: Deploy application to dev gcp
    needs: test-build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
          TELEMETRY: ${{ needs.test-build-and-push.outputs.telemetry }}

  deploy-dev-fss:
    name: Deploy application to dev fss
    needs: test-build-and-push
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/nais-dev-onprem.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
          TELEMETRY: ${{ needs.test-build-and-push.outputs.telemetry }}