name: Create release from branch
run-name: Create release from branch ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/poao-tilgang/actions/workflows/deploy-feature-dev.yaml

concurrency:
  group: create-release-from-branch
  cancel-in-progress: true

env:
  PRINT_PAYLOAD: true

jobs:
  test-build-and-push:
    name: Test, build and push
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'
      - name: Build maven artifacts
        run: mvn -B package

  create-release-for-branch:
    name: Deploy application to prod gcp and create release
    needs: [test-build-and-push]
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create Version
        run: echo "VERSION=$(TZ=\"Europe/Oslo\" date +%Y.%m.%d_%H.%M)-$(git rev-parse --short=12 HEAD)" >> $GITHUB_ENV
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'
      - name: Deploy release
        run: mvn -B -Drevision="${{ env.VERSION }}" -DskipTests source:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.VERSION }}
          tag_name: test:${{ env.VERSION }}
          prerelease: false
